### ISSUE TITLE
New version of primesieve available with possible performance improvements

### ISSUE THREAD

**Issue by BryanQuigley** [SChernykh/Amicable#5]
Not sure what kind of impact this will have on Amicable, but thought I'd mention it - cause it might improve performance..

It's not a drop in replacement - else I would have succeeded in trying it out.. Switches from OpenMP to C++ 11 threading, and does some other cleanup - https://github.com/kimwalisch/primesieve/blob/master/ChangeLog

The following files used in stdafx.h are gone:
primesieve/callback_t.hpp
primesieve/Callback.hpp
primesieve/PrimeFinder.hpp

And primesieve/SieveOfEratosthenes-inline.hpp was removed, used in Engine.cpp.

Thanks!

btw, a sample command for how to run amicable would in the Readme.md would be helpful for new users

**Comment by SChernykh** [comment]
primesieve/SieveOfEratosthenes-inline.hpp is my own modification to primesieve, it was never there originally. I'll try new primesieve version after new year, thanks for the heads up.

Regarding running amicable - you just run it without parameters and it outputs all amicable numbers up to the limit specified in SearchLimit::value in Definitions.h

**Comment by SChernykh** [comment]
Added a thorough description of command line parameters to the Readme.md

**Comment by SChernykh** [comment]
I've updated primesieve to the latest version. I didn't notice any change in performance though,
